title: Jekyll Staticman Test
author: yuceltoluyag
subtitle: Öldüren Yorumlar

url: "https://yuceltoluyag.github.io"
baseurl: "/jekyll-staticman"
staticman_url: https://minelyorum.herokuapp.com/v3/entry/github/yuceltoluyag/jekyll-staticman/main/comments
footer_only_homepage: true
footer_url: "https://github.com/yuceltoluyag/jekyll-staticman"
footer_text: "Bu sitede yer alan içerikler hayal ürünüdür."

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: "Fork"
    absolute-link: "https://github.com/yuceltoluyag/jekyll-staticman"
  - name: "Donate"
    absolute-link: "https://github.com/yuceltoluyag/"
